device: cuda
Loaded checkpoint: ./checkpoints_finetune_lambda0.01/best_epoch001.pth.tar
Frames:   0% 1/610 [00:01<13:00,  1.28s/it]
frame 0: mse=3.859194e-03 psnr=24.13503441984495 saved -> outputs/recon_frames/clip_01_padded/frame_00000.png
Frames:   0% 2/610 [00:02<12:33,  1.24s/it]
frame 1: mse=1.367671e-03 psnr=28.640182668503897 saved -> outputs/recon_frames/clip_01_padded/frame_00001.png
Frames:   0% 3/610 [00:03<12:10,  1.20s/it]
frame 2: mse=1.091985e-03 psnr=29.617833145440002 saved -> outputs/recon_frames/clip_01_padded/frame_00002.png
Frames:  73% 447/610 [08:36<02:42,  1.00it/s]/tmp/ipykernel_431/3388879869.py:161: RuntimeWarning: invalid value encountered in cast
  out_np = (x_hat[0].cpu().numpy().transpose(1,2,0) * 255.0).round().astype(np.uint8)
Frames: 100% 610/610 [09:14<00:00,  1.10it/s]
Done. frames: 610 avg_mse: nan avg_psnr (finite only): 20.667258144268196
Saved reconstructed frames to: outputs/recon_frames/clip_01_padded
